TRADE_SIZE = 100
EMA_ENTRY_THRESHOLD_HIGH = 0.012
EMA_ENTRY_THRESHOLD_MEDIUM = 0.055
WINDOW_HIGH = 100
WINDOW_MEDIUM = 275
MARKETS = ["ETHUSDT", "SOLUSDT", "INJUSDT", "NEARUSDT", "ENSUSDT", "JUPUSDT", "GMXUSDT", "HYPEUSDT", "AAVEUSDT", "UMAUSDT", "BCHUSDT", "LTCUSDT", "LINKUSDT"]