TRADE_SIZE = 100
LONG_RATIO = 2.0
SHORT_RATIO = 1.0
EMA_ENTRY_THRESHOLD_HIGH = 0.012
EMA_ENTRY_THRESHOLD_MEDIUM = 0.055
WINDOW_HIGH = 100
WINDOW_MEDIUM = 275
MARKETS = ["ETHUSDT", "SOLUSDT", "INJUSDT", "NEARUSDT", "ENSUSDT", "JUPUSDT", "GMXUSDT", "HYPEUSDT", "AAVEUSDT", "UMAUSDT", "BCHUSDT", "LTCUSDT", "LINKUSDT", "LDOUSDT"]